include classpath("application.conf")

node-address {
  protocol = http
  host = "*"
  port = 9324
  context-path = ""
}

rest-sqs {
  enabled = true
  bind-port = 9324
  bind-hostname = "0.0.0.0"
  sqs-limits = strict
}

aws {
  region = "ap-southeast-2"
  accountId = "000000000000"
}

queues {
  carematch-dead-letter { }
  carematch-ai-dead-letter { }
  compliance {
    defaultVisibilityTimeout = 65 seconds
    receiveMessageWait = 1 second
    deadLettersQueue {
      name = "carematch-dead-letter"
      maxReceiveCount = 3
    }
  }
  ai {
    defaultVisibilityTimeout = 130 seconds
    receiveMessageWait = 1 second
    deadLettersQueue {
      name = "carematch-ai-dead-letter"
      maxReceiveCount = 3
    }
  }
}
